### ISSUE TITLE
user is undefined

### ISSUE THREAD

**Issue by ajaybhatia** [lorensr/test-meteor-apollo#1]
Getting user undefined at server console while using playground

**Comment by lorensr** [comment]
Does setting the authorization header fix it?

https://github.com/apollographql/apollo-client/blob/lorensr/update-meteor-docs/docs/source/recipes/meteor.md#ide

**Comment by ajaybhatia** [comment]
> Does setting the authorization header fix it?
> 
> https://github.com/apollographql/apollo-client/blob/lorensr/update-meteor-docs/docs/source/recipes/meteor.md#ide
> 
> 
Yes it solves the issue. But in Apollo 2.0 it was not the case. If one logins using console on development client then user was available in graphql server.

No issues. I'm closing the issue and Mark it solved. Thank you very much for prompt reply.

**Comment by lorensr** [comment]
Yeah, we used to have GraphiQL with automatic auth, but we lost that with the upgrade to Apollo Server v2
